CREATE OR ALTER PROCEDURE sp_NV_ThanhToanDon
    @MaDon INT,
    @MaDM INT
AS
BEGIN
    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
    BEGIN TRANSACTION;
    BEGIN TRY
        IF EXISTS (SELECT 1 FROM DanhMuc WITH (UPDLOCK) WHERE MaDM = @MaDM)
        BEGIN
            UPDATE ChiTietDon SET TrangThai = N'Đã thanh toán' WHERE MaDon = @MaDon;
        END
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF ERROR_NUMBER() = 1205 ROLLBACK TRANSACTION; 
        ELSE ROLLBACK TRANSACTION;
    END CATCH
END;
GO

CREATE OR ALTER PROCEDURE sp_QL_XoaDanhMucAnToan
    @MaDM INT
AS
BEGIN
    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
    BEGIN TRANSACTION;
    BEGIN TRY
        IF EXISTS (SELECT 1 FROM DanhMuc WITH (UPDLOCK) WHERE MaDM = @MaDM)
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM ChiTietDon WHERE MaDM = @MaDM)
            BEGIN
                DELETE FROM DanhMuc WHERE MaDM = @MaDM;
            END
        END
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
    END CATCH
END;
GO
