CREATE OR ALTER PROCEDURE sp_QL_CapNhatGiaSP
    @MaMon INT,
    @GiaMoi DECIMAL(18,2)
AS
BEGIN
    BEGIN TRANSACTION;
    BEGIN TRY
        UPDATE DoUong SET Gia = @GiaMoi WHERE MaMon = @MaMon;
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
    END CATCH
END;
GO

CREATE OR ALTER PROCEDURE sp_NV_XemGiaTinhTien
    @MaMon INT
AS
BEGIN
    SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
    BEGIN TRANSACTION;
    BEGIN TRY
        SELECT TenMon, Gia FROM DoUong WHERE MaMon = @MaMon;
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
    END CATCH
END;
GO
