CREATE OR ALTER PROCEDURE sp_QL_CapNhatGiaSP
    @MaSanPham CHAR(4),
    @GiaMoi INT
AS
BEGIN
    BEGIN TRANSACTION;
    BEGIN TRY
        UPDATE Sanpham SET GiaBan = @GiaMoi WHERE MaSanPham = @MaSanPham;
        
        WAITFOR DELAY '00:00:10';

        ROLLBACK TRANSACTION; 
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    END CATCH
END;
GO

CREATE OR ALTER PROCEDURE sp_NV_XemGiaTinhTien
    @MaSanPham CHAR(4)
AS
BEGIN
    SET TRANSACTION ISOLATION LEVEL READ COMMITTED; 
    
    BEGIN TRANSACTION;
    BEGIN TRY
        SELECT TenSanPham, GiaBan 
        FROM Sanpham 
        WHERE MaSanPham = @MaSanPham;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO
